const APITEMPLATE_KEY = import.meta.env.VITE_APITEMPLATE_KEY;
const API_URL = 'https://rest.apitemplate.io/v2/create-pdf-from-html';

export const generateReceipt = async (operation) => {
  if (!APITEMPLATE_KEY) {
    console.warn('No APITemplate key provided');
    return null;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: 'Inter', -apple-system, sans-serif; color: #111; padding: 40px; margin: 0; }
        .header { display: flex; justify-content: space-between; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: 900; letter-spacing: 2px; }
        .title { font-size: 24px; color: #555; }
        .amount { font-size: 48px; font-weight: bold; margin: 20px 0; }
        .amount.positive { color: #10B981; }
        .amount.negative { color: #111; }
        .details-table { w-full; border-collapse: collapse; margin-top: 30px; }
        .details-table th, .details-table td { padding: 12px 0; border-bottom: 1px solid #eee; text-align: left; }
        .details-table th { color: #888; font-weight: 500; width: 40%; }
        .details-table td { font-weight: 600; }
        .footer { margin-top: 50px; text-align: center; color: #888; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">LUMEN</div>
        <div class="title">Transaction Receipt</div>
      </div>
      
      <div style="text-align: center;">
        <div style="color: #666; text-transform: uppercase; font-size: 14px; font-weight: bold; letter-spacing: 1px;">
          ${operation.type === 'transfer' ? 'Transfer' : operation.type === 'deposit' ? 'Deposit' : 'Payment'}
        </div>
        <div class="amount ${operation.type === 'deposit' ? 'positive' : 'negative'}">
          ${operation.type === 'deposit' ? '+' : '-'}${parseFloat(operation.amount || 0).toLocaleString()} ${operation.currency || 'CAD'}
        </div>
        <div style="display: inline-block; padding: 6px 12px; background: #f0fdf4; color: #16a34a; border-radius: 20px; font-weight: bold; font-size: 14px;">
          ${operation.status?.toUpperCase() || 'COMPLETED'}
        </div>
      </div>

      <table class="details-table" style="width: 100%;">
        <tr>
          <th>Transaction ID</th>
          <td>${operation.id}</td>
        </tr>
        <tr>
          <th>Date & Time</th>
          <td>${new Date(operation.created).toLocaleString()}</td>
        </tr>
        <tr>
          <th>Sender</th>
          <td>${operation.sender_name || 'LUMEN Bank'}</td>
        </tr>
        <tr>
          <th>Recipient</th>
          <td>${operation.recipient_name || '—'}</td>
        </tr>
        ${operation.description ? `
        <tr>
          <th>Description</th>
          <td>${operation.description}</td>
        </tr>` : ''}
      </table>

      <div class="footer">
        Generated by LUMEN Bank on ${new Date().toLocaleString()}
      </div>
    </body>
    </html>
  `;

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'X-API-KEY': APITEMPLATE_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        body: htmlContent,
        settings: {
          margin_top: "0.5in",
          margin_bottom: "0.5in",
          margin_left: "0.5in",
          margin_right: "0.5in",
          format: "A4"
        }
      })
    });

    if (!response.ok) {
      throw new Error(`APITemplate error: ${response.status}`);
    }

    const data = await response.json();
    if (data.status === 'success' && data.download_url) {
      return data.download_url;
    }
    
    throw new Error('Failed to generate PDF URL');
  } catch (error) {
    console.error('PDF Generation error:', error);
    return null;
  }
};
